/*
 * generated by Xtext
 */
package plantuml.eclipse.ui.contentassist

import plantuml.eclipse.ui.contentassist.AbstractPumlProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PumlProposalProvider extends AbstractPumlProposalProvider {
}
