/*
 * generated by Xtext
 */
package plantuml.eclipse.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PumlUiModule extends plantuml.eclipse.ui.AbstractPumlUiModule {
	public PumlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
