/*
* generated by Xtext
*/
package plantuml.eclipse;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PumlStandaloneSetup extends PumlStandaloneSetupGenerated{

	public static void doSetup() {
		new PumlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

