/*
 * generated by Xtext
 */
package plantuml.eclipse;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PumlRuntimeModule extends plantuml.eclipse.AbstractPumlRuntimeModule {

}
